import { Storage, KEYS } from '../utils/storage';
import { api } from '../utils/api';

interface JournalEntry {
  id: string;
  date: string;
  weight?: number;
  energy_level?: number;
  sleep_quality?: number;
  sleep_hours?: number;
  mood?: string;
  gym_activity?: {
    type: string;
    duration_mins: number;
    intensity: number;
  };
  notes?: string;
}

interface RecurringItem {
  item_id: string;
  name: string;
  type: string;
  doses_taken?: number;
  expected_doses?: number;
}

interface WeeklySummary {
  id: string;
  weekStart: string;
  weekEnd: string;
  generatedAt: string;
  summary: string;
  stats: {
    totalWorkouts: number;
    avgSleep: number;
    avgEnergy: number;
    avgMood: number;
    weightChange: number | null;
    doseAdherence: number;
    workoutStreak: number;
  };
  isAutoGenerated: boolean;
}

const MOOD_VALUES: Record<string, number> = { great: 5, good: 4, okay: 3, low: 2, bad: 1 };

export const WeeklySummaryService = {
  // Generate AI summary using backend
  generateAISummary: async (): Promise<string> => {
    const journal = await Storage.get<JournalEntry[]>(KEYS.JOURNAL_ENTRIES) || [];
    const items = await Storage.get<any[]>(KEYS.RECURRING_ITEMS) || [];
    
    try {
      const response = await api.post('/api/ai/summary', {
        journal_data: journal.slice(0, 14), // Last 2 weeks
        tracked_items: items.slice(0, 20),
      });
      return response.summary;
    } catch (error: any) {
      console.error('AI summary generation failed:', error);
      throw new Error('Failed to generate AI summary');
    }
  },

  // Calculate local stats for the week
  calculateWeeklyStats: async (): Promise<WeeklySummary['stats']> => {
    const journal = await Storage.get<JournalEntry[]>(KEYS.JOURNAL_ENTRIES) || [];
    const items = await Storage.get<any[]>(KEYS.RECURRING_ITEMS) || [];
    const workoutHistory = await Storage.get<string[]>(KEYS.WORKOUT_HISTORY) || [];
    
    const now = new Date();
    const weekAgo = new Date(now.getTime() - 7 * 24 * 60 * 60 * 1000);
    
    // Filter entries from last 7 days
    const weekEntries = journal.filter(e => {
      const entryDate = new Date(e.date);
      return entryDate >= weekAgo && entryDate <= now;
    });
    
    // Calculate stats
    const workoutsThisWeek = weekEntries.filter(e => (e.gym_activity?.duration_mins || 0) > 0);
    const sleepEntries = weekEntries.filter(e => e.sleep_quality);
    const energyEntries = weekEntries.filter(e => e.energy_level);
    const moodEntries = weekEntries.filter(e => e.mood);
    const weightEntries = weekEntries.filter(e => e.weight).sort((a, b) => new Date(a.date).getTime() - new Date(b.date).getTime());
    
    // Weight change (first entry vs last entry of the week)
    let weightChange: number | null = null;
    if (weightEntries.length >= 2) {
      weightChange = (weightEntries[weightEntries.length - 1].weight || 0) - (weightEntries[0].weight || 0);
    }
    
    // Workout streak calculation
    let streak = 0;
    const sortedWorkouts = [...workoutHistory].sort((a, b) => new Date(b).getTime() - new Date(a).getTime());
    const today = new Date().toISOString().split('T')[0];
    let checkDate = new Date(today);
    
    for (let i = 0; i < sortedWorkouts.length && i < 30; i++) {
      const expectedDate = checkDate.toISOString().split('T')[0];
      if (sortedWorkouts.includes(expectedDate)) {
        streak++;
        checkDate.setDate(checkDate.getDate() - 1);
      } else {
        break;
      }
    }
    
    // Dose adherence (simplified - % of active items with doses logged)
    const activeItems = items.filter(i => i.status === 'active');
    const doseAdherence = activeItems.length > 0 ? 
      (activeItems.filter(i => i.doses_taken > 0).length / activeItems.length) * 100 : 100;
    
    return {
      totalWorkouts: workoutsThisWeek.length,
      avgSleep: sleepEntries.length > 0 ? 
        sleepEntries.reduce((sum, e) => sum + (e.sleep_quality || 0), 0) / sleepEntries.length : 0,
      avgEnergy: energyEntries.length > 0 ? 
        energyEntries.reduce((sum, e) => sum + (e.energy_level || 0), 0) / energyEntries.length : 0,
      avgMood: moodEntries.length > 0 ? 
        moodEntries.reduce((sum, e) => sum + (MOOD_VALUES[e.mood || ''] || 0), 0) / moodEntries.length : 0,
      weightChange,
      doseAdherence: Math.round(doseAdherence),
      workoutStreak: streak,
    };
  },

  // Generate and save weekly summary
  generateAndSaveWeeklySummary: async (isAuto: boolean = false): Promise<WeeklySummary> => {
    const now = new Date();
    const weekStart = new Date(now.getTime() - 7 * 24 * 60 * 60 * 1000);
    
    const stats = await WeeklySummaryService.calculateWeeklyStats();
    let aiSummary = '';
    
    try {
      aiSummary = await WeeklySummaryService.generateAISummary();
    } catch (error) {
      // Fallback summary if AI fails
      aiSummary = WeeklySummaryService.generateFallbackSummary(stats);
    }
    
    const summary: WeeklySummary = {
      id: `summary_${Date.now()}`,
      weekStart: weekStart.toISOString().split('T')[0],
      weekEnd: now.toISOString().split('T')[0],
      generatedAt: now.toISOString(),
      summary: aiSummary,
      stats,
      isAutoGenerated: isAuto,
    };
    
    // Save to storage
    const summaries = await Storage.get<WeeklySummary[]>('peptrack_weekly_summaries') || [];
    summaries.unshift(summary);
    
    // Keep last 12 summaries (3 months)
    await Storage.set('peptrack_weekly_summaries', summaries.slice(0, 12));
    
    return summary;
  },

  // Get stored weekly summaries
  getWeeklySummaries: async (): Promise<WeeklySummary[]> => {
    return await Storage.get<WeeklySummary[]>('peptrack_weekly_summaries') || [];
  },

  // Get the most recent summary
  getLatestSummary: async (): Promise<WeeklySummary | null> => {
    const summaries = await WeeklySummaryService.getWeeklySummaries();
    return summaries.length > 0 ? summaries[0] : null;
  },

  // Check if we need to auto-generate a summary (e.g., hasn't been generated this week)
  shouldAutoGenerate: async (): Promise<boolean> => {
    const latest = await WeeklySummaryService.getLatestSummary();
    if (!latest) return true;
    
    const lastGenerated = new Date(latest.generatedAt);
    const now = new Date();
    const daysSinceLastSummary = (now.getTime() - lastGenerated.getTime()) / (1000 * 60 * 60 * 24);
    
    return daysSinceLastSummary >= 7;
  },

  // Generate fallback summary without AI
  generateFallbackSummary: (stats: WeeklySummary['stats']): string => {
    const parts: string[] = [];
    
    if (stats.totalWorkouts > 0) {
      parts.push(`You completed ${stats.totalWorkouts} workout${stats.totalWorkouts > 1 ? 's' : ''} this week.`);
      if (stats.workoutStreak > 1) {
        parts.push(`Great job maintaining a ${stats.workoutStreak}-day workout streak!`);
      }
    } else {
      parts.push('No workouts logged this week. Consider adding some physical activity to your routine.');
    }
    
    if (stats.avgSleep > 0) {
      const sleepQuality = stats.avgSleep >= 7 ? 'good' : stats.avgSleep >= 5 ? 'moderate' : 'below average';
      parts.push(`Your average sleep quality was ${sleepQuality} (${stats.avgSleep.toFixed(1)}/10).`);
    }
    
    if (stats.avgEnergy > 0) {
      parts.push(`Average energy levels: ${stats.avgEnergy.toFixed(1)}/10.`);
    }
    
    if (stats.weightChange !== null) {
      const direction = stats.weightChange > 0 ? 'gained' : 'lost';
      parts.push(`You ${direction} ${Math.abs(stats.weightChange).toFixed(1)} lbs this week.`);
    }
    
    if (stats.doseAdherence < 100) {
      parts.push(`Dose adherence: ${stats.doseAdherence}%. Try to stay consistent with your supplement schedule.`);
    } else {
      parts.push('Great job staying on track with your doses!');
    }
    
    return parts.join(' ');
  },

  // Check and auto-generate on app launch
  checkAndAutoGenerate: async (): Promise<WeeklySummary | null> => {
    if (await WeeklySummaryService.shouldAutoGenerate()) {
      try {
        return await WeeklySummaryService.generateAndSaveWeeklySummary(true);
      } catch (error) {
        console.error('Auto-generate summary failed:', error);
        return null;
      }
    }
    return null;
  },
};
